### ISSUE TITLE
Unhandled error when user inputs invalid error

### ISSUE THREAD

**Issue by aviskarkc10** [sbimochan/word-finder#7]
You get the following error when user inputs an invalid number.
```
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 42, in main
    get_permutation(letters, size)
  File "main.py", line 7, in get_permutation
    permutation = permutations(letter_list, length)
TypeError: Expected int as r
```
I would have solved this in my PR but wanted to see how you wanna go about it.
1. End the program right away with an error message
2. Continuously poll the user until they input valid number
3. Go with length of string for size if wrong number is given

**Comment by sbimochan** [comment]
I found your PR. Thank you for the contribution.

**Comment by sbimochan** [comment]
Why not in API branch too? 🤣

**Comment by aviskarkc10** [comment]
This is a new issue. That PR solved a different issue

**Comment by sbimochan** [comment]
There were two brances. One for API and one for CLI. I meant you could have changed in API too :p   
Now I’ve merged both branches and relected your code in API too. Thanks
